FB_EMAIL = "sydneysageivashkov24@gmail.com"
FB_PASSWORD = "saintjoseph1282004"
AZURE_OPENAI_API_KEY = "8P23czqAi428tPRIT66zw78BpnQp24TInpkJIhtgBju4WIQtENPgJQQJ99CDACHYHv6XJ3w3AAAAACOGfvAt"
AZURE_OPENAI_ENDPOINT = "https://quality-project-resource.openai.azure.com/openai/deployments/gpt-5.2-chat-2/chat/completions?api-version=2024-10-21"